spring:
   profiles:
      active: dev
      
## server port 
server:
   port: 3000

---

spring:
   profiles: dev
   datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      hikari:
         connectionTimeout: 20000
         maximumPoolSize: 5
         idleTimeout: 60000
         maxLifetime: 180000
   jpa:
      generate-ddl: true
      hibernate:
#         ddl-auto: create
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true
            show_sql: true
            enable_lazy_load_no_trans: true
            temp:
               use_jdbc_metadata_defaults: false
            dialect: org.hibernate.dialect.PostgreSQLDialect
   
## App Properties
app:
   jwtSecret: JWTSuperSecretKey
   jwtExpiration: 604800000

---

spring:
   profiles: prod
   datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      
server:
   port: 9000
